version: '3.8'

services:
  app:
    image: your-app-image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MEILISEARCH_HOST=http://meilisearch:7700
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
